import express from 'express';
import Hello from './Hello.js';
import Lab5 from './lab5.js';
import CourseRoutes from './Kanbas/Courses/routes.js';
import ModuleRoutes from './Kanbas/Modules/routes.js';
import AssignmentRoutes from './Kanbas/Assignments/routes.js';
import QuizRoutes from './Kanbas/Quizzes/routes.js';
import QuestionRoutes from './Kanbas/Questions/routes.js';
import cors from "cors";
const app = express();
app.use(cors());
app.use(express.json());
AssignmentRoutes(app);
QuizRoutes(app);
QuestionRoutes(app);
ModuleRoutes(app);
CourseRoutes(app)
Hello(app);
Lab5(app);
app.listen(process.env.PORT || 4000);